title: C5IN # Cameroon Cloud & Computing Innovation Network
email: contact@c5in.org # Change this
first_name: C5IN
description: >- # this means to ignore newlines until "baseurl:"
  Encourager la recherche dans les technologies du cloud computing, des systèmes distribués, de l'IoT Edge et du Fog au Cameroun. Notre objectif est de bâtir une communauté de chercheurs dynamique grâce à la formation, aux événements, à la collaboration et au partage de ressources.
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at https://username.github.io/reponame, set to /reponame
keywords: "C5IN, Cameroun, Cloud Computing, Réseau d'innovation, IoT Edge, Fog Computing, Systèmes distribués, Communauté de recherche, Éducation, Événements, Collaboration"
url: "https://c5in.github.io" # your site's domain, e.g., https://yourusername.github.io. Change this!
github_username: c5in # Change this
#linkedin_username: yourlinkedin # Optional


# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# see https://schema.org/docs/faq.html for more information
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

# For Google Analytics, see https://support.google.com/analytics/answer/10447272?hl=en&ref_topic=14088998&sjid=5129943941510317771-SA#zippy=%2Cgoogle-sites
# and follow the instructions for Google Sites. You will need to create a Google Analytics property and copy the Google tag ID.
google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)
pirsch_analytics: # your Pirsch analytics site ID (length 32 characters)
openpanel_analytics: # your Openpanel analytics client ID (format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)

# For Google Search Console, see https://support.google.com/webmasters/answer/9008080?hl=en#meta_tag_verification&zippy=%2Chtml-tag
google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out your bing-site-verification ID (Bing Webmaster)



future: true
awards:
  enabled: false
  max_awards: 5 # Maximum number of awards to display


pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

sponsors:
  enabled: true
testimonials:
  enabled: true
  limit: 6

members_config:
  defaults:
    placeholder: "https://placehold.co/150x150/1e5099/FFFFFF?text="
    image_path: "/assets/img/members/"
# Events
events_config:
  defaults:
    placeholder: "https://placehold.co/750x400/1e5099/FFFFFF?text="
    image_path: "/assets/img/events/" 

news_config:
  defaults:
    placeholder: "https://placehold.co/600x400?text="
    image_path: "/assets/img/news/"

stats:
  enabled: false
  items:
    - title: "Members"
      count: 100 # Update this with actual member count
      icon: "fa-users"
    - title: "Events"
      count: 50 # Update this with actual event count
      icon: "fa-calendar-alt"
    - title: "Publications"
      count: 20 # Update this with actual publication count
      icon: "fa-file-alt"
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

theme: null # We are building custom, but you could use a theme like minima or a remote_theme
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag # Uncomment if you add the gem

# Exclude from processing.
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - requirements.txt


# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/
  members:
    output: true
    permalink: /members/:title/ # title will be the filename without extension
  publications:
    output: true
    permalink: /publications/:year/:month/:day/:title/

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "C5IN Team" # Default author for posts
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "" # all files
    values:
      image_path: "/assets/images/" # Default path for images

# Site Navigation - used in _includes/header.html
# See _data/navigation.yml



# Social Media Links (optional, use in footer or header)
social:
  twitter: "YourTwitterHandle"
  github: "YourGitHubOrg"
  linkedin: "YourLinkedInPage"
  # facebook: "YourFacebookPage"