# .github/workflows/build-and-push-gh-pages.yml
name: Build Jekyll and Push to gh-pages

on:
  push:
    branches:
      - main # Ou 'master', ou la branche principale de votre projet

permissions:
  contents: write # Nécessaire pour créer/mettre à jour la branche gh-pages

jobs:
  build_and_push:
    name: Build and Push to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        # Assurez-vous que 'main' est bien votre branche de développement principale

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Choisissez une version compatible avec GitHub Pages et votre thème
          bundler-cache: true # Installe les dépendances et les met en cache

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ env.BASE_URL }}" # Construit le site
        env:
          JEKYLL_ENV: production
          # BASE_URL: ${{ secrets.BASE_URL }} # Décommentez si vous utilisez un baseurl dynamique.
          # Par exemple, si votre site est sur https://username.github.io/repository-name,
          # BASE_URL devrait être '/repository-name'. Vous pouvez le définir comme un secret
          # ou le laisser vide si votre site est à la racine (username.github.io).
          # Si votre _config.yml contient déjà le bon baseurl, vous n'avez pas besoin de cette variable ici.
          # Par défaut, si BASE_URL n'est pas défini, il sera une chaîne vide.
          BASE_URL: "" # Ajustez si votre site est dans un sous-répertoire (ex: /nom-du-repo)

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Le répertoire contenant les fichiers du site compilé
          publish_branch: gh-pages # La branche cible
          user_name: 'github-actions[bot]' # Nom de l'utilisateur pour le commit
          user_email: 'github-actions[bot]@users.noreply.github.com' # Email pour le commit
          commit_message: 'Automated build and deploy to gh-pages' # Message de commit
          force_orphan: true # Optionnel: Crée une branche 'gh-pages' orpheline (sans historique commun)
                             # pour garder cette branche propre avec seulement la dernière version du site.
                             # Peut être 'false' si vous préférez conserver l'historique.